Twitter_Django/Twitter_Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("twitterapp.urls")),
]

Twitter_Django/twitterapp/urls.py
from django.urls import path
from . import views
from .views import create_post

urlpatterns = [
    path("", views.posts_view, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create/", views.create_post, name='create_post'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('user/<str:username>/', views.user_page, name='user_page'),
    path('user/<str:username>/follow/', views.follow_user, name='follow_user'),  # URL for following a user
    path('user/<str:username>/unfollow', views.unfollow_user, name='unfollow_user'), # Unfollow
    path('following_users', views.following_users, name='following_users'), # See posts of users we follow
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('unlike/<int:post_id>/', views.unlike_post, name='unlike_post'),
]

Twitter_Django/twitterapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_admin = models.BooleanField(default=False)
    followers = models.ManyToManyField('self', symmetrical=False, related_name='following')
    def following_count(self):
        return self.following.count()

# Create post module
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, through='Like', related_name='liked_posts', blank=True)
    is_edited = models.BooleanField(default=False)  # Add a field to track if the post has been edited
    edited_text = models.TextField(blank=True, null=True)  # Field to store the edited content
    def __str__(self):
        return f'Posted by: {self.user.username} on {self.created_at}'
    def total_likes(self):
        return self.likes.count()
    
# Likes on posts
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    class Meta:
        unique_together = ('user', 'post')  # Ensure each user can like a post only once
    # Unlike
    @classmethod
    def unlike_post(cls, user, post):
        try:
            like = cls.objects.get(user=user, post=post)
            like.delete()
            return True  # Return True if unlike is successful
        except cls.DoesNotExist:
            return False  # Return False if like does not exist

Twitter_Django/twitterapp/forms.py
from django import forms 
from .models import Post 

class PostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ['text']
        

Twitter_Django/twitterapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import User, Post, Like
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse, Http404
from django.core.paginator import Paginator
from django.contrib import messages

def index(request):
    return render(request, "twitterapp/posts_view.html")

def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "twitterapp/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "twitterapp/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "twitterapp/register.html", {
                "message": "Passwords must match."
            })
        is_admin = request.POST.get("is_admin")  # Check if "is_admin" checkbox is checked
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            if is_admin:
                user.is_admin = True
            user.save()
        except IntegrityError:
            return render(request, "twitterapp/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "twitterapp/register.html")

# Create post
@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = PostForm()
    posts = Post.objects.all().order_by('-created_at')
    return render(request, "twitterapp/create_post.html", {'form': form, 'posts': posts})

# View posts page
def posts_view(request):
    posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-created_at')
    # return render(request, 'twitterapp/posts_view.html', {'posts': posts})

    # Paginate the posts
    paginator = Paginator(posts, 5)  # Display 5 posts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'twitterapp/posts_view.html', {'page_obj': page_obj})

# Like on posts
def like_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.likes.add(request.user)  # Add current user to post likes
    updated_likes_count = post.total_likes()
    return HttpResponse(updated_likes_count)

# User profile page with his posts
def user_page(request, username):    
    profile_user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(user=profile_user).order_by('-created_at')
    # posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-created_at')
    return render(request, 'twitterapp/user_page.html', {'profile_user': profile_user, 'posts': posts})

# Following functionality
def follow_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    request.user.following.add(user_to_follow)
    return redirect('user_page', username=username)

# Unfollow functionality
def unfollow_user(request, username):
    user_to_unfollow = get_object_or_404(User, username=username)
    request.user.following.remove(user_to_unfollow)
    return redirect('user_page', username=username)

# Show posts os users we follow
def following_users(request):
    if request.user.is_authenticated:
        following_users_ids = request.user.following.values_list('id', flat=True)
        posts = Post.objects.filter(user__in=following_users_ids).order_by('-created_at')
        return render(request, 'twitterapp/following_users.html', {'posts': posts})
    else:
        return render(request, 'twitterapp/login.html')

# Single post view - DOES NOT WORK (page wont render template)
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    print(post.text) # Print to console successful, but does not pass to template.
    return render(request, 'twitterapp/post_detail.html', {'post': post})

# Edit post functionality
@login_required
def edit_post(request, post_id):
    try:
        post = Post.objects.get(pk=post_id, user=request.user)    
    except Post.DoesNotExist:
        return HttpResponseRedirect(reverse('index'))
        #raise Http404("Post does not exist or you are not authorized to edit it.")       
    
    print("Post user ID:", post.user.id)
    print("Request user ID:", request.user.id)
    print("Post user:", post.user)
    print("Request user:", request.user)

    if post.user != request.user:
        messages.error(request, "You are not authorized to edit this post.")
        print("Redirecting to index page")
        return HttpResponseRedirect(reverse('index')) # or /
        # return HttpResponseRedirect(reverse("index"))
        #return redirect('posts_view')    
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            edited_post = form.save(commit=False)
            edited_post.is_edited = True
            edited_post.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = PostForm(instance=post)
    return render(request, 'twitterapp/edit_post.html', {'form': form, 'post': post})

@login_required
def unlike_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        Like.unlike_post(request.user, post)
        messages.success(request, 'Post unliked successfully.')
    except:
        messages.error(request, "unable to unlike post.")
    updated_likes_count = post.total_likes()
    return HttpResponse(updated_likes_count)

Twitter_Django/twitterapp/templates/twitterapp/create_post.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <div class="border mx-auto">
    <h3 class="margin_left20">Create a Post</h3>

    <form method="POST" class="margin_left20">
        <div class="col-sm-8 rounded-border">
            <h4>New Post</h4>
            {% csrf_token %}
            <div class="form-group">
                <textarea class="form-control" id="id_text" name="text" rows="3" placeholder="Enter text"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <h4 class="margin_left20">Latest Posts</h4>

    <ul>
        {% for post in posts %}
        <div class="col-sm-8">
            {{ post.text }}<br>
            <p id="font_small">Posted by <b>{{ post.user }}</b> <i>on {{ post.created_at }}</i></p>
            <hr>
        </div>
        {% endfor %}
    </ul>
    </div>

{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/edit_post.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <div class="border mx-auto">
    <h3 class="margin_left20">Edit Post</h3>

    <form method="POST" class="margin_left20">
        <div class="col-sm-8 rounded-border">
            <h4>New Post</h4>
            {% csrf_token %}
            <div class="form-group">
                <textarea class="form-control" id="id_text" name="text" rows="3" placeholder="Enter text">{{ post.text }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <h4 class="margin_left20">Latest Posts</h4>

    <ul>
        {% for post in posts %}
        <div class="col-sm-8">
            {{ post.text }}<br>
            <p id="font_small">Posted by <b>{{ post.user }}</b> <i>on {{ post.created_at }}</i></p>
            <hr>
        </div>
        {% endfor %}
    </ul>
    </div>

{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/following_users.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <h3 class="margin_left20">Posts of users you follow</h3>

    <ul id="posts-container">
        {% for post in posts %}
        <div class="col-sm-10">
            {{ post.text }}<br>     
            <i><span id="font_small">Posted by <b><a href="{% url 'user_page' username=post.user.username %}">{{ post.user.username }}</a></b> on {{ post.created_at }}</i></span><br>  
            <span class="font_small" id="likes_count_{{ post.id }}">{{ post.total_likes }}</span> <span class="font_small"> likes</span>
            <button class="like-btn" data-post-id="{{ post.id }}">Like</button>
            <hr>
        </div>
        {% endfor %}
    </ul>
    <div id="pagination-container">
        <button id="previous-btn">Previous</button>
        <button id="next-btn">Next</button>
    </div>    

{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/index.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <p class="margin_left20">TODO</p>
{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}TwitterApp{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'twitterapp/styles.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Like functionality
            document.querySelectorAll('.like-btn').forEach(function(button) {
                button.addEventListener('click', function() {
                    event.preventDefault(); // Prevent default form submission behavior
                    const postId = this.dataset.postId;
                    fetch(`/like/${postId}/`, {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}',
                        },
                    })
                    .then(response => {
                        if (response.ok) {
                            return response.text(); // Extract the response text
                        } else {
                            throw new Error('Network response was not ok.');
                        }
                    })
                    .then(data => {
                        // Update the like count in the DOM
                        const likeCountElement = document.getElementById(`likes_count_${postId}`);
                        if (likeCountElement !== null) {
                            likeCountElement.textContent = data; // Update the like count
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
                });
            });
        })

            // Unlike
            function unlikePost(postId) {
                fetch(`/unlike/${postId}/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                })
                .then(response => {
                    if (response.ok) {
                        return response.text();
                    } else {
                        throw new Error('Network response was not ok.');
                    }
                })
                .then(data => {  
                    console.log("Data output:", data);
                    const likeCountElement = document.getElementById(`likes_count_${postId}`);
                    if (likeCountElement !== null) {
                        likeCountElement.textContent = data;
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('An error occurred while processing your request.');
                });
            }

        // Event listener for unlike button click
            document.addEventListener('DOMContentLoaded', function() {
                document.querySelectorAll('.unlike-btn').forEach(function(button) {
                    button.addEventListener('click', function(event) {
                        event.preventDefault();
                        event.stopPropagation(); // Stop event propagation
                        const postId = this.dataset.postId;
                        unlikePost(postId);
                    });
                });
            });

    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">TwitterApp</a>          
        <div>
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    {% if user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_page' user.username %}">Admin: <strong>{{ user.username }}</strong></a>
                    </li>
                    {% else %}                    
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                    {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_post' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'following_users' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="body">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

Twitter_Django/twitterapp/templates/twitterapp/login.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <div class="col-sm-4 rounded-border text-center mx-auto">
        <h3>Login</h3>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>

        <p>Don't have an account? <a href="{% url 'register' %}">Register here.</a></p>
    </div>
{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/post_detail.html
<!-- Cant display this page, dunno why this error apperas. -->

{% extends "twitterapp/layout.html" %}

{% block content %}

    <h1>Post Detail</h1>

        {{ post.text }}
        <!-- Add any other post details you want to display -->


{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/posts_view.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <h3 class="margin_left20">Latest Posts</h3>

    <ul id="posts-container">
        <!-- Display posts -->
        {% for post in page_obj %}
        
            <div class="col-sm-10">
                {{ post.text }}<br>     
                <i><span id="font_small">Posted by <b><a href="{% url 'user_page' username=post.user.username %}">{{ post.user }}</a></b> on {{ post.created_at }} 
                    {% if user.is_authenticated and post.user == request.user %}
                        <a href="{% url 'edit_post' post_id=post.id %}">Edit Post</a>
                    {% endif %}                
                </i></span><br>  
                <span class="font_small" id="likes_count_{{ post.id }}">{{ post.total_likes }}</span> <span class="font_small"> likes</span>
                {% if user.is_authenticated %}
                    <button class="like-btn" data-post-id="{{ post.id }}">Like</button> <button type="button" class="unlike-btn" data-post-id="{{ post.id }}">Unlike</button>

                {% endif %}            
                <hr>
            </div>
        
        {% endfor %}
    
        <!-- Pagination -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </ul>
    
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/register.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <div class="col-sm-4 rounded-border text-center mx-auto">
        <h3>Register</h3>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <div class="form-group">
                <input type="checkbox" name="is_admin" class="margin_right20">Register as admin
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>

        <p>Already have an account? <a href="{% url 'login' %}">Log In here.</a></p>
    </div>
{% endblock %}

Twitter_Django/twitterapp/templates/twitterapp/user_page.html
{% extends "twitterapp/layout.html" %}

{% block body %}
    <div class="border mx-auto">
        <h3 class="margin_left20">Profile for {{ profile_user.username }}</h3><br>
        {% if profile_user.is_admin %}
        <span class="margin_left20">{{ profile_user.username }} is admin.</span><br>
        {% else %}
        <span class="margin_left20">{{ profile_user.username }} is not admin.</span><br>
        {% endif %}
        <span class="margin_left20">Email: {{ profile_user.email }}</span> <br>  

        <span class="margin_left20" id="font_small">Followers: {{ profile_user.followers.all|length }}.
            {% for follower in profile_user.followers.all %}
                {{ follower.username }},       
            {% empty %}
                No followers found.
            {% endfor %}
        </span><br>
        <span class="margin_left20" id="font_small">Following: {{ profile_user.following_count }}.
            {% for followed_user in profile_user.following.all %}
                {{ followed_user.username }},
            {% empty %}
                No users followed.
            {% endfor %}
        </span>
        <!-- Follow Button Form -->
        {% if user.is_authenticated %}
            {% if request.user != profile_user %}
                {% if request.user in profile_user.followers.all %}
                <form class="margin_left20" method="post" action="{% url 'unfollow_user' profile_user.username %}">
                    {% csrf_token %}
                    <button class="follow-btn" type="submit">Unfollow</button>
                </form>
                {% else %}
                    <form class="margin_left20" method="post" action="{% url 'follow_user' profile_user.username %}">
                        {% csrf_token %}
                        <button class="follow-btn" type="submit">Follow</button>
                    </form>
                {% endif %}
            {% endif %}
        {% endif %}
        <br><hr>
        <h5 class="margin_left20">Posts made by {{ profile_user.username }}:</h5><br>
        <ul>        
            {% for post in posts %}
            <div class="col-sm-8">
                {{ post.text }}<br>
                <p id="font_small">Posted by <b>{{ post.user }}</b> <i>on {{ post.created_at }}</i></p>
                <hr>
            </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}